export type Spacing = {
   xs: number;
   sm: number;
   md: number;
   lg: number;
   xl: number;
   '2xl': number;
   '3xl': number;
   '4xl': number;
   '5xl': number;
   '6xl': number;
   '7xl': number;
   '8xl': number;
   '9xl': number;
};
export type Width = {
   sm: number;
   medium: number;
   lg: number;
   xl: number;
   xxl: number;
   small: number;
   large: number;
   extraLarge: number;
   tiny: number;
   huge: number;
   nano: number;
   micro: number;
   mega: number;
   giga: number;
   ultra: number;
   mini: number;
   maxi: number;
   jumbo: number;
   super: number;
   grand: number;
   immense: number;
   colossal: number;
};

export type Height = {
   'h-1/2': string;
   'h-1/3': string;
   'h-2/3': string;
   'h-1/4': string;
   'h-2/4': string;
   'h-3/4': string;
   'h-1/5': string;
   'h-2/5': string;
   'h-3/5': string;
   'h-4/5': string;
   'h-1/6': string;
   'h-5/6': string;
   'h-1/7': string;
   'h-2/7': string;
   'h-3/7': string;
   'h-4/7': string;
   'h-5/7': string;
   'h-6/7': string;
   'h-1/8': string;
   'h-3/8': string;
   'h-5/8': string;
   'h-7/8': string;
   'h-1/9': string;
   'h-2/9': string;
   'h-4/9': string;
   'h-5/9': string;
   'h-7/9': string;
   'h-8/9': string;
   'h-1/10': string;
   'h-3/10': string;
   'h-7/10': string;
   'h-9/10': string;
   'h-1/12': string;
   'h-5/12': string;
   'h-7/12': string;
   'h-11/12': string;
   'h-full': string;
};

export type FontSize = {
   'text-xs': number;
   'text-sm': number;
   'text-base': number;
   'text-lg': number;
   'text-xl': number;
   'text-2xl': number;
   'text-3xl': number;
   'text-4xl': number;
   'text-5xl': number;
   'text-6xl': number;
   'text-7xl': number;
   'text-8xl': number;
   'text-9xl': number;
};

export type Sizes = {
   spacing: Spacing;
   width: Width;
   height: Height;
   fontSize: FontSize;
};
